require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target "RegattaBoard" do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  target "RegattaBoardTests" do
    inherit! :complete
    # Pods for testing
  end
end

target "RegattaBoard-tvOS" do
  # Pods for RegattaBoard-tvOS

  target "RegattaBoard-tvOSTests" do
    inherit! :search_paths
    # Pods for testing
  end
end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == "React"
#       target.remove_from_project
#     end
#   end
# end
